# Generated by Django 5.1.4 on 2024-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
