# Generated by Django 5.1.4 on 2024-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_product_slug_alter_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="first_app.producttag"),
        ),
    ]
